services:
  frontend:
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
      args:
        - APP=frontend
    image: coin-crusade-game-fe
    container_name: coin-crusade-game-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: docker/nestjs/Dockerfile
      args:
        - APP=backend
    image: coin-crusade-game-be
    container_name: coin-crusade-game-be
    ports:
      - "3001:3001"
    depends_on:
      - database
  database:
    container_name: coin-crusade-game-database-rs0
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

volumes:
  mongo_data:
  mongo_config:
