services:
  node:
    build: docker/dev
    user: ${COMPOSE_UID-1000}:${COMPOSE_GID-1000}

  # For interactive development
  node_shell:
    container_name: node_shell
    extends: node
    entrypoint: bash
    ports:
      - ${COMPOSE_START_PORT-8080}:${COMPOSE_START_PORT-8080}
    volumes:
      - .:/application:z
