/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/api': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['AppController_getHello']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/log': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['GameLogsController_saveGameLogs']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/predict': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['NeuralNetworkController_predict']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export type components = {
  schemas: {
    Log: {
      chunkLostLives: number
      chunkElapsedSeconds: number
      chunkGainedSeconds: number
      chunkPickedCoins: number
      chunkGeneratedCoins: number
      chunkMapDifficulties: string[]
      chunkPlatformSpeed: number
      chunkDifficultySkore: number
      gameTotalElapsedSeconds: number
      gameTotalGainedSeconds: number
      gameEngine: string
      engineSuggestedAction?: string
      /** Format: date-time */
      chunkCreated: string
    }
    GameLogDto: {
      logs: components['schemas']['Log'][]
    }
    NeuralNetworkDto: {
      chunkLostLives: number
      chunkElapsedSeconds: number
      chunkGainedSeconds: number
      chunkPickedCoins: number
      chunkGeneratedCoins: number
      chunkMapDifficulties: string[]
      chunkPlatformSpeed: number
      chunkDifficultySkore: number
      gameTotalElapsedSeconds: number
      gameTotalGainedSeconds: number
      gameEngine: string
      engineSuggestedAction?: string
      /** Format: date-time */
      chunkCreated: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = {
  AppController_getHello: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  GameLogsController_saveGameLogs: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GameLogDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  NeuralNetworkController_predict: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NeuralNetworkDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
