services:
  database:
    container_name: coin-crusade-game_db-dev
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: ../../docker/postgres/Dockerfile
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - 'dev_postgres_data:/var/lib/postgresql/data'

volumes:
  dev_postgres_data:
    driver: local
