services:
  database:
    container_name: dev_rs0
    build:
      context: .
      dockerfile: ../../docker/postgres/Dockerfile
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - 'dev_postgres_data:/var/lib/postgresql/data'

volumes:
  dev_postgres_data:
    driver: local
