export * from './emotion-registry'
export * from './game-configuration-registry'
export * from './menu-registry'
export * from './snackbar-registry'
export * from './initial-animation-registry'
export * from './socket-registry'
